#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Obtener archivos modificados y ejecutar hooks por scope
CHANGED_FILES=$(git diff --cached --name-only)

for file in $CHANGED_FILES; do
  case $file in
    packages/icons/*)
      echo "🔍 Ejecutando hooks para @mp-front/icons..."
      npx lerna run lint --scope="@mp-front/icons" --stream
      npx lerna run build --scope="@mp-front/icons" --stream 2>/dev/null || true
      ;;
  esac
done